baseURL = "https://violinist-frank-26710.netlify.com/"
languageCode = "en-us"
title = "Bananer är goda"
theme = "ananke"
SectionPagesMenu = "main"

[params]
 featured_image = "images/baes.jpg"
 twitter = "https://twitter.com/t4ostra"